### PR TITLE
summary: Update note about default graphics mode

### PR DESCRIPTION
**Pull request by crawfxrd**
Only oryp4 will default to integrated graphics mode. All models with Turing and newer cards will default to hybrid graphics mode.

### CODE REVIEW

**Comment by jackpot51** [comment]
Can you replace the right side as mentioned by @WatchMkr:

> When we have hybrid by default, I think we should add a line for launching on the nvidia GPU and replace the monitor graphic with a graphic on the right-click menu for launching on the GPU.

**Comment by crawfxrd** [comment]
gis-summary

**Comment by crawfxrd** [comment]
Updated the new image to include the icon with the screenshot from @jacobgkau.

gis-summary

**Comment by crawfxrd** [comment]
You can run `/usr/libexec/gnome-initial-setup --existing-user` to test.

**Comment by jackpot51** [comment]
Merged to get it built in launchpad. Will only release once @isantop tests

**Comment by isantop** [comment]
This is the summary page on my Oryx 4: 

image

**Pull request merged**
