### PR TITLE
feat: Add new pages for Pop 21.04

### LINKED ISSUE #72: User Desktop Config on 21.04 Upgrade
Designs here under "User Upgrade to 21.04" https://www.figma.com/file/F3QQlV7BYsj0Zwq9WhWnqg/Desktop-Dreams?node-id=1898%3A7723

### PR DESCRIPTION
**Pull request by mmstick**
Requires https://github.com/pop-os/desktop-widget/pull/19 to be merged / released

Closes #72

### CODE REVIEW

**Review by jackpot51 — COMMENTED** [review]
Currently, if this runs in a user's environment, it resets some of the settings like extending the dock. It probably will go unnoticed, but may indicate a bug in the initial state of the settings, and I'd prefer it loaded the initial state from dconf

**Comment by jackpot51** [comment]
I'm also curious if you want to re-use https://github.com/pop-os/desktop-widget/ (written in Rust ;-) for the two settings pages here. It may make this easier and require less code.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Testing this now. Will this repository need a `master_focal` branch so this doesn't affect 20.04?

**Comment by jackpot51** [comment]
Yes, this will need to be master_hirsute

**Comment by maria-komarova** [comment]
@mmstick what visuals did you use for the Launcher and Gesture pages? I have both static images and video files for them depending on how close we are to trying video files there.

**Comment by jacobgkau** [comment]
@maria-komarova The following .png images are currently being used:
- https://github.com/pop-os/gnome-initial-setup/blob/8c7f635d31a4d76da941514b803207c4a325d04f/gnome-initial-setup/pages/pop-launcher/pop-launcher.png 
Screenshot from 2021-06-23 15-44-22

- https://github.com/pop-os/gnome-initial-setup/blob/8c7f635d31a4d76da941514b803207c4a325d04f/gnome-initial-setup/pages/pop-gesture/pop-gesture.png 
Screenshot from 2021-06-23 15-44-25

**Comment by maria-komarova** [comment]
Great, thanks for confirming. I still have videos in case we have time to experiment with those, just let me know.

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
Switching to videos would be done in desktop-widget now, since this takes the pages generated there.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The recent change to start after upgrade seems to be working-- any beta users will also see GIS after installing this update, but only once per account.

It sounds like we're waiting on an additional page to support https://github.com/pop-os/upgrade/pull/176. Since the static pages like the [gesture page](https://github.com/pop-os/gnome-initial-setup/blob/e548b2bb52c241ac33bf62727776033cabd2daea/gnome-initial-setup/pages/pop-gesture/gis-pop-gesture-page.c) are located in this PR, I'm assuming the extensions page will also require additional changes here unless anyone says otherwise.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
2927705 failed to build on the build server. It does build locally.

**Comment by jacobgkau** [comment]
2927705 failed to build on the build server. It does build locally.

**Comment by jackpot51** [comment]
I made master_focal and master_groovy branches, so this can safely hit master

**Review by jacobgkau — APPROVED** [review]
Tested with https://github.com/pop-os/desktop-widget/pull/26.

**Pull request merged**
