### PR TITLE
Set panel text based on default graphics mode

### PR DESCRIPTION
**Pull request by crawfxrd**
system76-power now has the logic for determining the default graphics mode for a system. Remove the hard-coded models and call PowerDaemon's `GetDefaultGraphics()` and `ExternalDisplaysRequireDGPU()` to provide the correct information.

Requires: pop-os/system76-power#204
Requires: pop-os/system76-power#205

### CODE REVIEW

**Comment by jacobgkau** [comment]
galp5 (NVIDIA) before:
Screenshot from 2020-12-21 09-21-37

galp5 (NVIDIA) after:
Screenshot from 2020-12-21 09-22-08

Right now, this is making the message less specific, which would be a regression. galp5 NVIDIA can use external displays in Integrated mode, so it's confusing that the message says "to _potentially_ use external displays, switch to Hybrid or NVIDIA graphics." We should hopefully still be able to tell whether or not that's necessary with the same degree of precision as before the change.

Also, "Integrated" and "Hybrid" were capitalized in the old message (and still are in the first message on the left), but are no longer capitalized in the new message.

**Comment by crawfxrd** [comment]
I would say the way before was worse, because it *only* worked for oryp4. But I will need to add another method to system76-power to check _if_ external displays require NVIDIA graphics to improve the message. (It current only emits a signal _when_ a graphics switch is needed.)

**Review by jacobgkau — APPROVED** [review]
The correct message is displaying on galp5, addw2, and oryp4.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
galp5 is not displaying the correct text right now, and I'm getting a warning in the terminal about a dbus call failing. This is with system76-power version `7bdc841` installed from master staging, which should have the correct dbus methods.

Screenshot from 2021-01-07 09-13-04

Testing with `dbus-send`, I am able to call `GetExternalDisplaysRequireDGPU`, but I'm not able to call `GetDefaultGraphics`. I get the same `failed to read sysfs info: No such file or directory` message (which is strange, because my notes indicated I was able to call it while testing https://github.com/pop-os/system76-power/pull/206.)

**Comment by crawfxrd** [comment]
This is caused by `get_nvidia_device()` in system76-power. It tries to read `/sys/module/nvidia/version` to check if the driver supports run-time power management, which will fail if it boots using integrated graphics.

**Comment by jacobgkau** [comment]
On gaze15 and galp5 (with https://github.com/pop-os/system76-power/pull/213), this is now working if I run gnome-initial-setup using `/usr/libexec/gnome-initial-setup --existing-user` or by creating and logging into a new user account. However, if I perform the installation, then chroot in and install this update before the first boot, I'm not shown any of the default graphics pages, but am instead shown the generic "ready to use Pop!_OS" page.

Looking at journalctl, I see the dbus calls to `system76-power` failing:
```
Jan 28 08:47:24 pop-os dbus-daemon[846]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.67" (uid=108 pid=1511 comm="/usr/libexec/gnome-initial-setup " label="unconfined") interface="com.system76.PowerDaemon" member="GetSwitchable" error name="(unset)" requested_reply="0" destination="com.system76.PowerDaemon" (uid=0 pid=893 comm="/usr/bin/system76-power daemon " label="unconfined")
Jan 28 08:47:24 pop-os gnome-initial-s[1511]: DBus call failed: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.67" (uid=108 pid=1511 comm="/usr/libexec/gnome-initial-setup " label="unconfined") interface="com.system76.PowerDaemon" member="GetSwitchable" error name="(unset)" requested_reply="0" destination="com.system76.PowerDaemon" (uid=0 pid=893 comm="/usr/bin/system76-power daemon " label="unconfined")
Jan 28 08:47:24 pop-os dbus-daemon[846]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.67" (uid=108 pid=1511 comm="/usr/libexec/gnome-initial-setup " label="unconfined") interface="com.system76.PowerDaemon" member="GetSwitchable" error name="(unset)" requested_reply="0" destination="com.system76.PowerDaemon" (uid=0 pid=893 comm="/usr/bin/system76-power daemon " label="unconfined")
Jan 28 08:47:24 pop-os gnome-initial-s[1511]: DBus call failed: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.67" (uid=108 pid=1511 comm="/usr/libexec/gnome-initial-setup " label="unconfined") interface="com.system76.PowerDaemon" member="GetSwitchable" error name="(unset)" requested_reply="0" destination="com.system76.PowerDaemon" (uid=0 pid=893 comm="/usr/bin/system76-power daemon " label="unconfined")
```

I see a similar failure from pop-upgrade earlier:
```
Jan 28 08:47:21 pop-os pop-upgrade[1102]: checking if pop-upgrade requires an update
Jan 28 08:47:21 pop-os pop-upgrade[1102]: pop-upgrade: dbus client error
Jan 28 08:47:21 pop-os pop-upgrade[1102]:   caused by: calling UpdateCheck method failed
Jan 28 08:47:21 pop-os pop-upgrade[1102]:   caused by: "Rejected send message, 1 matched rules; type=\"method_call\", sender=\":1.29\" (uid=108 pid=1102 comm=\"/usr/bin/pop-upgrade release check \" label=\"unconfined\") interface=\"com.system76.PopUpgrade\" member=\"UpdateCheck\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.system76.PopUpgrade\" (uid=0 pid=860 comm=\"/usr/bin/pop-upgrade daemon \" label=\"unconfined\")"
Jan 28 08:47:21 pop-os dbus-daemon[846]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.29" (uid=108 pid=1102 comm="/usr/bin/pop-upgrade release check " label="unconfined") interface="com.system76.PopUpgrade" member="UpdateCheck" error name="(unset)" requested_reply="0" destination="com.system76.PopUpgrade" (uid=0 pid=860 comm="/usr/bin/pop-upgrade daemon " label="unconfined")
Jan 28 08:47:21 pop-os systemd[1090]: pop-upgrade-notify.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 08:47:21 pop-os systemd[1090]: pop-upgrade-notify.service: Failed with result 'exit-code'.
```

I don't see anything that would specifically block the `gnome-initial-setup` user from making dbus calls, but it's not explicitly allowed. If I edit `/etc/dbus-1/system.d/system76-power.conf` and duplicate the `adm`/`sudo` policy for `user=gnome-initial-setup`, then it works on first boot. I think that file needs to be changed in the system76-power PR: https://github.com/pop-os/system76-power/blob/master/data/system76-power.conf

**Review by jacobgkau — APPROVED** [review]
Now working after the last commit to https://github.com/pop-os/system76-power/pull/213, tested them together.

**Pull request merged**
