### PR TITLE
Summary image

### PR DESCRIPTION
**Pull request by jackpot51**
This disables the language page in all modes, and updates the summary page image to:

ready-to-go

### CODE REVIEW

**Comment by jacobgkau** [comment]
After this change, the initial "Welcome!" page is also gone, and the first thing I see is the dock layout option:

Screenshot from 2022-01-20 19-13-04

Is this intentional?

**Comment by jacobgkau** [comment]
On orpy8 (regular 1080p display), the last page got wider-- it looks like the `Launch using Dedicated Graphics Card` image is not scaled as it should be:

Screenshot from 2022-01-20 12-14-41

**Comment by jackpot51** [comment]
> After this change, the initial "Welcome!" page is also gone, and the first thing I see is the dock layout option:
> 
> Screenshot from 2022-01-20 19-13-04
> 
> Is this intentional?

Yes, this is intentional. @WatchMkr can confirm

**Comment by jackpot51** [comment]
> On orpy8 (regular 1080p display), the last page got wider-- it looks like the `Launch using Dedicated Graphics Card` image is not scaled as it should be:
> 
> Screenshot from 2022-01-20 12-14-41

I will fix this soon, thanks

**Review by jacobgkau — APPROVED** [review]
The image issue shown in the last screenshot is fixed.

Confirmed that if I select a non-English language during installation, that language is applied to the user account when I log in, without needing to set it via GNOME Initial Setup.

When I create a new user via Settings, the new user is no longer prompted to select a language, so it's stuck with the system default (that the first user set at installation) unless the first user changes it in Settings after creation. I suppose this is a fairly safe assumption, as anyone sharing a computer would probably either speak/read the same language or would be able to ask the first user to change it for them if it was really necessary.

When I log in with a non-admin account (who does not have permissions to change the graphics mode), I see the new summary image on the last page:

Screenshot from 2022-01-20 14-21-36

This also shows up for all users on a non-switchable-graphics system.

**Pull request merged**
