### PR TITLE
Release issues

### LINKED ISSUE #69: Make location services opt-in rather than enabled by default

### LINKED ISSUE #73: Initial setup missing timezone pages.
In the latest [ISO 21.04  #12] (https://buildchain.system76.com/job/pop-os/job/debug/job/21.04/lastBuild/)  the new pages look great, but the setup is missing the timezone select functions found in previous versions. At the moment Automatic timezone switching isn't working (see: https://github.com/pop-os/pop/issues/1736) so we need to give users the option to set their timezone manually.

### LINKED ISSUE #75: gnome-inital-setup launches once the iso reaches the desktop.
Latest debug [ISO 21.04 pop-os/iso#12](https://buildchain.system76.com/job/pop-os/job/debug/job/21.04/lastBuild/) launches gnome-initial-setup on first boot (before the install)

### PR DESCRIPTION
**Pull request by mmstick**
Closes #69 
Closes #73 
Closes #75

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Confirmed the following:
- Location services are now disabled by default (#69 is fixed)
- The timezone page now shows up, after the location services (privacy) page (#73 is fixed)

To test #75, I added a user with a uid of 995. I still had GIS start when I logged in with that user.

**Comment by leviport** [comment]
Should the UID comparison be `>= 1000`? My user account on my main install has a UID of 1000, where as the live disk user "pop-os" has a UID of 999.

**Comment by mmstick** [comment]
Wrong value was returned for a UID match. Changed to named constant so `CHECK_EXIT` is returned, that is the correct value to signal to exit.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Built locally to test, GIS is no longer starting when logging into the system user with a UID of 995. The other two issues are still fixed.

**Pull request merged**
