### PR TITLE
summary: Add galp5 for switchable graphics

### PR DESCRIPTION
**Pull request by crawfxrd**
galp5 has an Intel-only and an NVIDIA variant. Check if either driver is loaded for showing the graphics switching info.

### CODE REVIEW

**Comment by jackpot51** [comment]
Testing if nvidia or nouveau module is loaded is what we do elsewhere, see system76-power/src/graphics.rs

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
I'm getting this when trying to install for testing:

```
system76@pop-os:~$ apt policy pop-gnome-initial-setup
pop-gnome-initial-setup:
  Installed: 3.36.1~1593716052~20.10~e07a263
  Candidate: 3.36.1~1608072110~20.10~c3ebc16
  Version table:
     3.36.1~1608072110~20.10~c3ebc16 1002
       1002 http://apt.pop-os.org/staging/galp5 groovy/main amd64 Packages
 *** 3.36.1~1593716052~20.10~e07a263 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
system76@pop-os:~$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
system76@pop-os:~$ sudo apt install pop-gnome-initial-setup=3.36.1~1608072110~20.10~c3ebc16
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-gnome-initial-setup : Depends: libpop-theme-switcher (>= 0.1.1) but 0.1.1~1607014660~20.10~66b6888 is to be installed
E: Unable to correct problems, you have held broken packages.
system76@pop-os:~$ apt policy libpop-theme-switcher
libpop-theme-switcher:
  Installed: 0.1.1~1607014660~20.10~66b6888
  Candidate: 0.1.1~1607014660~20.10~66b6888
  Version table:
 *** 0.1.1~1607014660~20.10~66b6888 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
system76@pop-os:~$ 
```

It looks like a versioning issue with a dependency, will this still be an issue after this is out of staging?

Also, I downloaded and force-installed with `dpkg`, and am still not seeing the switchable-graphics page in GIS. This machine defaults to Integrated mode in distinst, so the check for `nvidia` or `nouveau` will not return true, because neither of those modules are loaded in integrated mode. (If I reboot into Hybrid mode, then it does show up, but we would want this to show on the first boot since that's when GIS typically runs.)

**Comment by ids1024** [comment]
Looks like the same issue as https://github.com/pop-os/gnome-control-center/issues/133

Hold off on merging this until I've updated the `libpop-theme-switcher` package. Then this branch can be rebuilt, and the resulting package shouldn't have that issue.

**Comment by jacobgkau** [comment]
Levi confirmed that the Intel galp5 returns `not switchable` when running `system76-power graphics switchable`, while the NVIDIA galp5 returns `switchable` even in Integrated mode where the current module check isn't working, so perhaps that could be used instead of the module check like Tim had mentioned previously. I know there was a concern about not wanting switchable things to display on random non-System76 hardware, but it looks like we're using the model whitelist in addition to the `is_nvidia_loaded()` function right now, so a model whitelist + `is_switchable()` function might be what we need here in GIS.

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
As expected, I did not get the switchable graphics prompt on the UMA galp5.

**Review by jacobgkau — APPROVED** [review]
Switchable page now shows up on NVIDIA model even when booted into Integrated mode, and the page includes the message about switching to Hybrid mode to utilize GPU offloading. Page does not show up on Intel model.

**Pull request merged**
